version: '3.3'
services:
  jenkins:
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/${USER_NAME}/jenkins_configuration:/var/jenkins_home
    build:
      context: jenkins
      dockerfile: Dockerfile
    privileged: true
    restart: always
