pipeline {
    agent any
    environment {
        DOCKER_IMAGE_NAME = "my-python-image"
        DOCKER_IMAGE_TAG = "latest"
        CONTAINER_NAME = "my-python-job"
    }
    stages {
        stage('Build Docker image') {
            steps {
                sh 'docker build -t ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} -f python_job/Dockerfile python_job/'
            }
        }
        stage('Run Docker container') {
            steps {
                sh 'docker run ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}'
            }
        }
    }
}
