version: '3.3'
services:
  jenkins:
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    env_file:
      - .env
#    environment:
#      DOCKER_HOST: "tcp://docker:2376"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    restart: always
